### PR TITLE
StarGo driver working with Wifi

### PR DESCRIPTION
**Pull request by ken-self**
Had to make a lot of changes due to StarGo sending additional responses on a state change.  
To fix I brought in as much of the I/O code into a central place so I can flush out these additional responses reliably. (tcflush is not enough on its own)
Some of these changes more rightly belong on LX200telescope as they just put a class wrapper around the static LX200driver functions.
Currently tidying up code and working on why the track mode/enable keeps reverting to off

### CODE REVIEW

**Comment by sterne-jaeger** [comment]
On which mount and firmware version are you working? I checked it against my Linear with StarGO 5.66beta but it already fails in the initialization. See the attached gzipped log file.
[log_18-02-44.txt.gz](https://github.com/sterne-jaeger/indi/files/2281112/log_18-02-44.txt.gz)

**Comment by ken-self** [comment]
Not sure if I replied to the right place so trying some other addresses

-------- Forwarded Message --------
Subject: 	Re: [sterne-jaeger/indi] StarGo driver working with Wifi (#1)
Date: 	Mon, 13 Aug 2018 07:08:52 +1000
From: 	Ken <ken.kgself@gmail.com>
Reply-To: 	ken.kgself@gmail.com
To: 	sterne-jaeger <notifications@github.com>



That's with an M-Uno Firmware 5.6.6 andI was using the Wifi connection

The code I used was built on x64 VM

Yours is timing out on almost every command except those where no 
timeout is set (due to no response). I didn't do anything special as 
regards the low level read/writes except to always use the transmit() 
and receive() functions for all I/O. In the debug messages where it does 
a sendQuery it indicates if it will WAIT for a response or NOWAIT

I'll try it out on USB connection and also build on a Raspberry Pi to 
see whats happening. Could be a comms issue

This is interesting. Looks like I've messed up the error handling on the 
handshake so it should fail to connect when it can't get a response.

[2018-08-12T18:03:22.427 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Active Snoop, driver: Dome Simulator, property: 
DOME_PARK "
[2018-08-12T18:03:22.428 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Connecting to /dev/ttyUSB0 "
[2018-08-12T18:03:22.428 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Port FD 7 "
[2018-08-12T18:03:22.428 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Connection successful, attempting handshake... "
[2018-08-12T18:03:22.429 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Avalon StarGo: Sendquery :GR# WAIT "
[2018-08-12T18:03:22.429 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Avalon StarGo Sending Command ':GR#' "
[2018-08-12T18:03:26.358 CEST INFO ][ org.kde.kstars.indi] - Avalon 
StarGo :  "[WARNING] Avalon StarGo Failed to receive full response: 
Timeout error. (Return code: -4) "
[2018-08-12T18:03:26.373 CEST INFO ][ org.kde.kstars.indi] - Avalon 
StarGo :  "[ERROR] Avalon StarGo: Unable to parse RA response  "
[2018-08-12T18:03:26.380 CEST INFO ][ org.kde.kstars.indi] - Avalon 
StarGo :  "[INFO] Avalon StarGo is online. "
[2018-08-12T18:03:26.390 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Configuration successfully saved for DEVICE_PORT. "
[2018-08-12T18:03:26.391 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Configuration successfully saved for DEVICE_BAUD_RATE. "
[2018-08-12T18:03:26.392 CEST DEBG ][ org.kde.kstars.indi] - Avalon 
StarGo : "[DEBUG] Configuration successfully saved for CONNECTION_MODE. "
[2018-08-12T18:03:26.392 CEST INFO ][ org.kde.kstars.ekos] - Avalon 
StarGo is connected.
[2018-08-12T18:03:26.393 CEST DEBG ][ org.kde.kstars.ekos] - 1  devices 
connected out of  1

**Comment by ken-self** [comment]
It gets further on my RPi3. Once I set the correct port anyway. It then 
stops communicating after a minute or so. I wonder if its a memory leak

**Comment by sterne-jaeger** [comment]
Do you use the USB connection on your RPI3? On mine it runs mostly fine. From time to time I get timeouts, but it's not really an issue.

I build it under Raspbian from scratch.

**Comment by ken-self** [comment]
Yes. I'm trying to run two small computers. One on the dec axis (x64 Aaeon-Up CORE) for the cameras then the RPI3 on the RA axis controlling the mount and chained wirelessly to the Aaeon one. That was the plan anyway but earth loops or interference on the Wifi channel caused me to try the StarGo wifi connection directly from the Aaeon.
I had the same issue RPI3 that you saw but that was because I was choosing the wrong USB port. Then I pulled the latest INDI code and rebuilt the Avalon driver when I saw some integration issues with the cameras. That worked better but is failing on the call to the libindi procedure get_local_sidereal_time. So now I'm rebuilding everything as its probably a linkage problem.
I'm running the RPi3 on Ubuntu Mate 16.04

**Comment by ken-self** [comment]
Just rebuilt libindi and tried to rebuild the avalon driver but I'm getting: 
CMakeFiles/indi_lx200stargo.dir/home/ken/indi/libindi/drivers/telescope/lx200telescope.cpp.o:(.data.rel.ro+0x3c): undefined reference to `INDI::Telescope::ISSnoopDevice(_xml_ele*)'
collect2: error: ld returned 1 exit status
CMakeFiles/indi_lx200stargo.dir/build.make:175: recipe for target 'indi_lx200stargo' failed
make[2]: *** [indi_lx200stargo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/indi_lx200stargo.dir/all' failed
make[1]: *** [CMakeFiles/indi_lx200stargo.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ken-self** [comment]
Finally got the rebuild to complete. But still getting a problem with get_local_sidereal_time (in LiBNova). If I bypass the call and instead get LST from the mount then everything works. If StarGo can calculate LST this is probably a better way to go. But presumably we need to set the Local Date/Time, Time Zone and Longitude so StarGo can calculate it?
Or I could use conditional compiles for ARM vs x86 and x64.

**Comment by sterne-jaeger** [comment]
Hm, I am running Debian 6.3.0-18+deb9u1 in a virtual machine on my Macbook, which has a Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz installed. Here the source code compiles fine.
Which libnova version is installed on your x64?

We should leave LST calculation in the driver. Using StarGo as calculation backend might not be the best idea...

**Comment by ken-self** [comment]
Latest changes now compile and build on Ubuntu 16.04 VM on x64 and RPi3 Ubuntu Mate 16.04. The code runs on the x64 using the call to get_local_sidereal_time (which is in libindi - indicom.c) but this is currently bypassed in the last commit and replaced with a request to StarGo. I agree this is not the preferred approach. (Although I don't think its serious as long as StarGo is provided UTC date/time and longitude) 
On RPi3 the code consistently halts on the call but works with the bypass in place. 
Reverting the last commit (or commenting the request to StarGo in getLSTString)  restores the preferred behaviour. As a temporary fix I could just hack in some LST calculation code till I sort out the linkage problem. I probably need to rebuild from scratch using the latest libindi to start with.
On both RPi3 and on x64 libnova-dev is at 0.14.0-2.1

Are you able to run the latest code on RPi3 both with and without the bypass?
Also can you rebase the stargo_work branch on your repo? - its a long way behind the master now

**Comment by ken-self** [comment]
I can call the libnova procedures directly from the driver and everything works. So libnova is ok. 
In indicom.c the definition of get_local_sidereal_time depends on HAVE_LIBNOVA being defined.  I figured I must have run cmake before I installed libnova so I deleted build/libindi and reran cmake. In the log it says it found libnova. The I rebuilt libindi
But when I rebuild the driver it still fails in the call to get_local_sidereal_time. I'm not sure where HAVE_LIBNOVA  gets defined but I think it must be missing for the ARM devices. Time to post to the main forum

The latest commit calls libnova directly to calculate sidereal. Works reliably on RPi3 and x64.

**Comment by sterne-jaeger** [comment]
HAVE_LIBNOVA is defined by the run of cmake, so please delete everything inside your build directory and rerun make. You need to do this both for building libindy and for 3rdparty.

**Comment by sterne-jaeger** [comment]
Ken,
I would like to rebase to v1.7.4 of libindi. Maybe this resolves some issues. If everything runs perfect, I will do the rebase tonight.

**Comment by sterne-jaeger** [comment]
Rebase to v1.7.4 of libindi done.
